version: '3.1'

services:
  db:
    image: postgres:9.6.9
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:4.0.10
    ports:
      - 6379:6379

volumes:
  postgres-data: