# Generated by Django 2.2.5 on 2019-09-23 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('device_id', models.CharField(db_index=True, max_length=128, unique=True)),
                ('device_name', models.CharField(choices=[('phone', 'phone'), ('desktop', 'desktop'), ('laptop', 'laptop'), ('etc', 'etc'), ('pad', 'pad')], db_index=True, max_length=12)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
